<?php
/**
 * @author Erol Soyöz <erol@soyoz.com>
 */
 
namespace Soyoz\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
}
