soyoz_blog:
    resource: "@SoyozBlogBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /user

# app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
