soyoz_blog_homepage:
    path:       /
    defaults:   { _controller: SoyozBlogBundle:Blog:index }

soyoz_blog_admin:
    path:       /admin
    defaults:   { _controller: SoyozBlogBundle:Admin:index }
    
soyoz_blog_list:
    path:       /list
    defaults:   { _controller: SoyozBlogBundle:Blog:list }

soyoz_blog_show:
    path:       /{slug}
    defaults:   { _controller: SoyozBlogBundle:Blog:show }
