soyoz_blog_homepage:
    path:       /
    defaults:   { _controller: SoyozBlogBundle:Blog:index }

soyoz_blog_admin:
    path:       /admin
    defaults:   { _controller: SoyozBlogBundle:Admin:index }

soyoz_blog_admin_post:
    resource: "@SoyozBlogBundle/Resources/config/routing/post.yml"
    prefix:   /admin/post

soyoz_blog_show:
    path:       /{slug}
    defaults:   { _controller: SoyozBlogBundle:Blog:show }
